[package]
name = "rust"
version = "0.1.0"
authors = ["Pavel <pavel.shackih@gmail.com>"]
edition = "2018"

[dependencies]
jni = {version = "0.12.2", default-features = false }

[lib]
name = "rust"
crate-type = ["cdylib"]